version: "2"

run:
  timeout: 3m
  tests: true
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - misspell
  settings:
    misspell:
      locale: US


issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports